---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: fedora-27

suites:
  - name: default
    run_list:
      - recipe[monitoring::default]
    attributes:

  - name: autochef
    run_list:
      - recipe[monitoring::autochef]
    attributes:
