name 'prometheus'
maintainer 'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license 'WTFPL'
description 'Installs/Configures prometheus'
long_description 'Installs/Configures prometheus'
version '0.2.0'

depends 'packagecloud'
depends 'porta_user'
depends 'openssh'
depends 'firewall'
