name 'monitoring'
maintainer 'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license 'WTFPL'
description 'Installs/Configures monitoring'
long_description 'Installs/Configures monitoring'
version '0.1.0'

depends 'prometheus'
depends 'porta_user'
depends 'openssh'
depends 'firewall'
